### ISSUE TITLE
Import num-traits dependency as no-std

### ISSUE THREAD

**Issue by brandon-powell** [barafael/as5600-rs#1]
I'm fairly new to the cargo/crate system, so this may be a misunderstanding on my part, but I think there is an issue w/the `num-traits` dependence import. When used in an embedded arm (thumb) context, it fails to compile (with an error related to `std`).

I was able to fix this with a local branch by changing the dependency to look like:

```toml
num-traits = {version = "0.2.14", default-features=false}
```

**Comment by barafael** [comment]
You're totally right.
I must have overlooked this somehow, added it after testing with microcontroller perhaps?!
If you like, you can submit a fix, else I'll do it when I get back home :)

**Comment by barafael** [comment]
@brandon-powell thanks for reporting! Fixed.
