### ISSUE TITLE
e-hal@v1 support

### ISSUE THREAD

**Issue by barafael** [barafael/as5600-rs#5]

**Comment by brainstorm** [comment]
Hey, I saw you starred my recent Rust AVR AS5600 repo using your crate and now I just saw this issue! :)

Would it make sense to implement traits from [embedded_hal_async I2c instead](https://docs.rs/embedded-hal-async/latest/embedded_hal_async/i2c/index.html). I'm targetting embassy and perhaps a non-blocking impl could be more interesting for this use case and also in general?

/cc @jubeormk1

**Comment by barafael** [comment]
Both make sense

**Comment by barafael** [comment]
I'm going over my driver crates and this one is next! Unless PR :)

**Comment by brainstorm** [comment]
Please go ahead, I think it'd take me more time to understand how to integrate sync and async I2C and PR than if you implement it. I'm currently reading some resources and it's unclear (to me) which route to take and how to implement it properly:

https://github.com/therealprof/display-interface/pull/48
https://github.com/rust-embedded/embedded-hal/issues/50
https://ferrous-systems.com/blog/async-on-embedded/#from-blocking-to-non-blocking

/cc @jubeormk1

**Comment by barafael** [comment]
upcoming crates.io release 0.7.0 with e-hal (blocking) support @brainstorm

**Comment by barafael** [comment]
@brainstorm the v0.8.0 release has the feature "async". Please let me know if it works for you!

**Comment by brainstorm** [comment]
Thanks heaps for adding this in record speed! Unfortunately I'm still facing a panic when querying the `u16` angle value both when the sensor is connected to my Atmega2560 I2C pins and when there's no sensor connected at all... I suspect it's [not a problem with your crate though](https://github.com/brainstorm/embassy-as5600/commit/f21edb908262a86ec66a54187284c8b9f9ea547a), I'll have to keep investigating and/or ask Rust AVR experts like @Rahix:

```shell
$ cargo build
WARN rustc_codegen_ssa::back::link Linker does not support -no-pie command line option. Retrying without.
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.16s

$ simavr --mcu atmega2560 target/avr-atmega2560/debug/embassy-avr-as5600-encoder.elf
Loaded 10124 .text at address 0x0
Loaded 3242 .data
Reading angle.
Firmware panic!..
  At src/main.rs:63:38..
^Csignal caught, simavr terminating
```

The code above is essentially trying to [read the sensor angle on the loop](https://github.com/brainstorm/embassy-as5600/blob/2850f9ce0ece571441aba87d8ca6d8ce9a6c0820/src/main.rs#L61-L66):

```rust
(...)
    loop {
        ufmt::uwriteln!(&mut serial, "{}", "Reading angle").unwrap();
        let status = encoder.angle().unwrap();
        ufmt::uwriteln!(&mut serial, "{}", "Angle has been read").unwrap_infallible();
        ufmt::uwriteln!(&mut serial, "{}", status).unwrap_infallible();
    }
```

**Comment by barafael** [comment]
Can you not unwrap the results and print them instead? If that doesn't work because of ufmt, then match on the result and print at least which variant it was

**Comment by brainstorm** [comment]
Thanks! [Just did that](https://github.com/brainstorm/embassy-as5600/commit/06de1e8d521da9fd1ff9521657733b050136445c) and seems to be about comms (`as5600::error::Error::Communication`), doesn't panic now. I've attached the oscilloscope and I can see the `0x36` I2C packet sent by the board but no response from the sensor.

Tomorrow I'll solder the 100nF & 1nF caps recommended by the datasheet and try again :)

**Comment by barafael** [comment]
I thought so. Likely the Comms error will be an underlying i2c nak error. Btw of course it doesn't panic if you don't unwrap :) you have pull-ups in place?

**Comment by brainstorm** [comment]
> I thought so. Likely the Comms error will be an underlying i2c nak error. Btw of course it doesn't panic if you don't unwrap :) you have pull-ups in place?

Heh, yes indeed I should have written the `match` before asking... I should check whether embassy::main accepts Result<(), Error> as return as it'd make the code cleaner (using the ? operator and no unwraps)... but I've not come across no_std examples using result on main perhaps it's not supported or portable? Learning as I go, thanks for your insights! :)

Probably Result is not common in `no_std` because it complicates the unwind logic and has a major storage (code) footprint? I don't know enough about this topic :-S

Anyway, yes, I'm using a RAMPS 1.4 hat so it does have a couple of 4K7 resistors installed for pull-ups (on D20/D21):

https://reprap.org/wiki/File:RAMPS1.4schematic.png

**Comment by barafael** [comment]
I don't think returning a result from main in embedded is a good idea. Where does it return to?

Unless you make it another function and call that one from main of course. 

But it sounds like you have different problems rn :) let me know how it goes :)
